### ISSUE TITLE
Repository Beschreibung unausgefüllt

### ISSUE THREAD

**Issue by almereyda** [cwoomi/cert-covid19#3]
Hallo @cwoomi ,

danke für diese ausführliche Sammlung!

Ich habe etwas ähnliches erstellt, und dabei festgestellt, dass die Überschrift

> Informationssammlung zum Thema CoVid-19

wunderbar als Repositorybeschreibung fungieren könnte. Dann würde diese auch in Snippets und Vorschauen des Links angezeigt.

Siehe

- https://meta.allmende.io/t/desaster-response-for-social-resilience/601

Vielleicht ist das die zwei Klicks wert. Danke!

**Comment by almereyda** [comment]
Auch Tags könnten die allgemeine Auffindbarkeit erleichtern, wie bspw.:

Tag | Anzahl
--- | ---
~~https://github.com/topics/corona~~ | ~~117~~, zu allgemein
https://github.com/topics/coronavirus | 422
https://github.com/topics/covid-19 | 466
https://github.com/topics/covid19 | 143
https://github.com/topics/covid | 43
https://github.com/topics/covid-2019 | 29
https://github.com/topics/2019-ncov | 108
https://github.com/topics/ncov | 57
https://github.com/topics/ncov-2019 | 34
https://github.com/topics/covid-virus | 58

Ein paar einschlägig davon genügen vielleicht?

- coronavirus
- covid-19
- 2019-ncov

erschienen mir als eine günstige Auswahl.

**Comment by cwoomi** [comment]
Da hatte ich gar nicht dran gedacht, danke - ist nun ausgefüllt =)
