### ISSUE TITLE
More dashboards

### ISSUE THREAD

**Issue by fospald** [cwoomi/cert-covid19#7]
https://qap.ecdc.europa.eu/public/extensions/COVID-19/COVID-19.html
https://who.maps.arcgis.com/apps/opsdashboard/index.html#/ead3c6475654481ca51c248d52ab9c61
my development: https://www-user.tu-chemnitz.de/~feo/private/covid-19/

**Comment by cwoomi** [comment]
done - die ersten beiden hinzugefügt, das letzte mal nicht, weil Quelle = privat
